name: KeyHunt Automation

on:
  workflow_dispatch:  # Manually Run
  push:
    branches:
      - main

jobs:
  run-keyhunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y git build-essential
          git clone https://github.com/Ramavatar98/keyhunt-automation.git
          cd keyhunt-automation
          make legacy

      - name: Run KeyHunt
        run: |
          ./keyhunt -m address  -f tests/66.txt -b 66 -l compress -q -s 10

      - name: Check for KeyFound
        run: |
          if [ -f KEYFOUNDKEYFOUND.txt ]; then
            echo "Key Found! Saving..."
            TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
            echo "[$TIMESTAMP] $(cat KEYFOUNDKEYFOUND.txt)" >> found_keys.log

            # Commit Data
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add found_keys.log
            git commit -m "New key found on $TIMESTAMP"
            git push

            # Send Email Notification
            echo "New Key Found: $(cat KEYFOUNDKEYFOUND.txt)" | mail -s "New Key Found!" g98655545@gmail.com

            rm KEYFOUNDKEYFOUND.txt
          fi
          
