name: KeyHunt Auto Restart & Resume

on:
  workflow_dispatch:  # Manually Start Karne Ke Liye
  push:
    branches:
      - main

jobs:
  run-keyhunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y git build-essential
          git clone https://github.com/Ramavatar98/keyhunt-.git
          cd keyhunt-
          make legacy

      - name: Resume Previous Run (If Exists)
        run: |
          if [ -f last_position.txt ]; then
            echo "Resuming from last saved position..."
            LAST_POS=$(cat last_position.txt)
          else
            echo "Starting from scratch..."
            LAST_POS=1
          fi
          echo "Last Position: $LAST_POS"
        id: resume_step

      - name: Run KeyHunt
        timeout-minutes: 350  # 5 hours 50 minutes (5 * 60 + 50)
        run: |
          cd keyhunt-
          ./keyhunt -m address -f tests/66.txt -b 66 -l compress -q -s 10 -r ${{ steps.resume_step.outputs.LAST_POS }} | tee -a keyhunt_output.log

      - name: Save Progress
        run: |
          LAST_POS=$(grep "Current position:" keyhunt-/keyhunt_output.log | tail -n1 | awk '{print $NF}')
          echo $LAST_POS > last_position.txt
          git add last_position.txt
          git commit -m "Saving last checked position: $LAST_POS"
          git push

      - name: Check for "Hit! Private Key:"
        run: |
          if grep -q "Hit! Private Key:" keyhunt-/keyhunt_output.log; then
            echo "Private Key Found! Saving..."
            TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
            grep "Hit! Private Key:" keyhunt-/keyhunt_output.log >> found_keys.log

            # Commit & Push Found Keys
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add found_keys.log
            git commit -m "New Private Key Found on $TIMESTAMP"
            git push
          fi

      - name: Auto Restart Workflow (After 5h 50m)
        if: always()
        run: |
          echo "Restarting workflow..."
          gh workflow run "KeyHunt Auto Restart & Resume" --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
